services:
  app: 
    image: fastapi_analytics_app
    build:
      context: .
      dockerfile: Dockerfile.web
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    # environment:
    #   - PORT=8002
    #   - DATABASE_URL=postgresql+pyscopg2://fastapi_user:fastapi_password@db:5432/fastapi_db
    env_file:
      - .env
    ports:
      - "8002:8002"
    restart: unless-stopped
    volumes:
      - ./src:/code:rw
    develop: 
      watch:
        - action: rebuild
          path: Dockerfile.web
        - action : rebuild
          path: requirements.txt
        - action: rebuild
          path: compose.yml
    depends_on:
      - db_service
  # https://qiita.com/Ryo-0131/items/25d75106b2f5e082be37
  # postgresql+pyscopg2://fastapi_user:fastapi_password@db:5432/fastapi_db
  db_service:
    image: timescale/timescaledb:latest-pg17
    restart: always
    environment:

      - POSTGRES_USER=time-user
      - POSTGRES_PASSWORD=time-user
      - POSTGRES_DB=timescaledb
#      - TS_TUNE_MEMORY=8GB # free -m | grep 'Mem' | awk '{print $2}'
    ports:
      - "5432:5432"
    # expose:
    #   - "5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
volumes:
  timescaledb_data:

